### PR TITLE
fix: populate complete entity data in deletion event webhooks

### LINKED ISSUE #2125: Empty fields in task.assignee.deleted event webhook
### Description

When deleting an assignee from a task, the `name` and `username` fields of the `assignee` object are empty in the output of the `task.assignee.deleted` webhook. 

I would expect these to include the complete data, as it does in the `task.assignee.created` event.

```json
{
  "event_name": "task.assignee.deleted",
  "time": "2026-01-20T17:05:19.864947849Z",
  "data": {
    "assignee": {
      "created": "0001-01-01T00:00:00Z",
      "id": 1,
      "name": "",
      "updated": "0001-01-01T00:00:00Z",
      "username": ""
    },
```

### Vikunja Version

v1.0.0-rc3-243-606d10f9

### Browser and version

_No response_

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by kolaente**
## Summary

Fixes webhook payloads for deletion events that were previously containing incomplete or empty entity data. This occurred because entities were being deleted from the database before the webhook event was dispatched.

## Changes

This PR implements four targeted fixes to ensure complete entity data in deletion event webhooks:

### 1. TaskAssignee Deletion (`pkg/models/listeners.go`)
- Extended `reloadEventData()` to fetch full assignee user data by ID
- Webhook payload now includes complete user object (username, email, timestamps, etc.)

### 2. TaskComment Deletion (`pkg/models/task_comments.go`)
- Modified `Delete()` to call `ReadOne()` before deletion
- Ensures comment text, author, and timestamps are included in webhook payload
- Follows the same pattern used by `Task.Delete()` and `TaskAttachment.Delete()`

### 3. TaskAttachment Deletion (`pkg/models/task_attachment.go`)
- Extended `ReadOne()` to fetch the `CreatedBy` user
- Webhook payload now includes file creator information

### 4. TaskRelation Deletion (`pkg/models/task_relation.go`)
- Modified `Delete()` to fetch complete relation including `CreatedBy` user before deletion
- Webhook payload now includes relation timestamps and creator information

## Testing

- ✅ All existing tests pass (83 PASS, 0 FAIL)
- ✅ No regressions detected in feature test suite
- ✅ Changes follow existing patterns from `Task.Delete()` and `TaskAttachment.Delete()`

## Note

The linter reports that `reloadEventData()` now has a cyclomatic complexity of 32 (threshold is 30). This is a minor increase from the pre-existing complexity. If desired, this can be addressed in a follow-up PR by refactoring the function to extract reload logic into helper functions.

Fixes #2125

### CODE REVIEW

File: pkg/models/task_comments.go [hunk 1]
```diff
@@ -118,7 +118,17 @@ func (tc *TaskComment) CreateWithTimestamps(s *xorm.Session, a web.Auth) (err er
...
-func (tc *TaskComment) Delete(s *xorm.Session, _ web.Auth) error {
+func (tc *TaskComment) Delete(s *xorm.Session, a web.Auth) error {
+	// Fetch full comment BEFORE deletion
+	err := tc.ReadOne(s, a)
+	if err != nil {
+		return err
+	}
+
+	// Store author for doer field
+	author := tc.Author
```
Comment (kolaente) [inline pkg/models/task_comments.go]: This should be the a user, not the author

File: pkg/models/task_relation.go [hunk 2]
```diff
@@ -315,6 +314,13 @@ func (rel *TaskRelation) Delete(s *xorm.Session, a web.Auth) error {
 		}
 	}
 
+	// Fetch CreatedBy user
+	fullRelation.CreatedBy, err = user.GetUserByID(s, fullRelation.CreatedByID)
```
Comment (kolaente) [inline pkg/models/task_relation.go]: this should happen in ReadOne

**Comment by kolaente** [comment]
auggie review
